### ISSUE TITLE
[recap] 스트림을 왜 사용해야 할까? 

### ISSUE THREAD

**Issue by rootTiket** [Leets-Official/modern-java-in-action#1]
### 무엇을 알게 되었나요?

스트림을 사용하는 큰 이유는 코드 가독성이겠지만 성능 면에서는 어떻게 우수한가를 중심으로 알아보았다.
특히 스레드 프로그래밍의 관점에서 어떠한가에 중점을 두고 살펴보았다.

### ✏️ 스트림이 뭐야?
>한 번에 하나씩 생성되는 연속적인 데이터 항목들의 모임

### ❓  뭐가 좋을까?
>스트림은 공장같이 순차적인 공정으로 이루어져 있지만 각 공정은 독립적으로 작업을 처리하게 된다. 
>JAVA의 스트림 API 를 사용하면 이러한 병렬처리를 스레드, 락을 사용하지 않고 해낼 수 있다!

### 병렬처리에서 중요한 것
>스레드를 통해 병렬 처리를 하려고 할때 가장 고민해야 할 부분 공유자원을 동시에 접근하려고 할때 어떤 순서로 접근하게 하는가? 이다.
<br/>

예를들어 스레드 A와 스레드 B가 하나의 변수 k에 접근하려고 할때 A는 k의 값을 1로 저장하려 할 때 B가 k의 값이 업데이트 되기 전에 읽어버릴 수도 있다.

이런 경우 특정한 결과 값을 보장하지 못할 수도 있다! (선 후 관계를 보장받지 못하기 때문)

동시성 이슈를 해결하기 위해 JAVA에서는 Synchronized라는 키워드를 제공하여 해당 코드 블록에 하나의 스레드만 접근 할 수 있게 만들어준다.

1. 스레드는 락을 얻고 공유 자원 공간에 접근 한다. 
2. 스레드가 동작을 완료하면 락을 반환한다.
3. 만약 스레드가 공유 자원 공간에 접근하려고 할 때 락이 없다면 대기 큐에 들어가서 대기를 한다.
4. 2번 동작 이후 반환 된 락이 있으면 다음 순서 스레드가 락을 획득하고 공유 자원 공간에 접근한다.

위와 같은 메커니즘은 동시성을 해결 할 수 있지만 스레드가 다른 스레드로 교체되는 컨텍스트 스위치가 일어나 오버헤드를 발생시켜 성능을 떨어뜨린다.

스트림을 사용하는 것으로 이러한 문제를 해결 할 수 있게 된다.

이렇게 스트림으로 처리하게 되면 filter와 collect를 병렬적으로 처리 할 수 있게된다.

### 어째서 스트림이 병렬처리에 유리한가?

> 메서드를 값처럼 전달하게 되면 공유 객체 자체와는 상호작용을 하지 않기 떄문이다

메서드 자체를 직접 참조하게 되기 때문에 위에서 말한 공유하는 자원 공간에는 다른 스레드가 접근 할 수 있게 되는 원리

또한 하나의 작업을 서브 작업으로 나누어 작업하는 방식을 사용해 더 좋은 성능을 낼 수 있다.

두 가지 일을 동시에 한다면 한 작업은 앞에서 부터 뒤로, 다른 작업은 뒤에서 앞으로 진행 하는 식으로 동시에 진행 할 수 있게 된다.

정리하자면 스레드는 코드 가독성 뿐 만 아니라 병렬처리 하기 유리한 코드라는 것과 기존 공유 자원을 보호하는 Synchronized의 성능을 보완 할 수 있다고 할 수 있다.

### 이해를 위해 노력한 부분

1.4.1 자바의 병렬성과 공유되지 않은 가변 상태 
> 흔히 사람들은 자바의 병렬성은 어렵고 synchronized는 쉽게 에러를 일으킨다고 생각한다. 자 바 8은 어떤 요술방망이를 제공할까? 자바 8은 두 가지 요술방망이를 제공한다. 우선 라이브러리에서 분할을 처리한다. 즉, 큰 스트 림을 병렬로 처리할수 있도록 작은 스트림으로 분할한다. 또한 filter 같은 라이브러리 메서드 로 전달된 메서드가 상호작용을 하지 않는다면 가변 공유 객체를 통해 공짜로 병렬성을 누릴 수 있다. 상호작용을 하지 않는다는 제약은 프로그래머 입장에서 상당히 자연스러운 일이다(예를 들어 Apple：：isGreenApple을 생각해보자). 함수형 프로그래밍에서 함수형이란 ‘함수를 일급값 으로 사용한다’라는 의미도 있지만 부가적으로 ‘프로그램이 실행되는 동안 컴포넌트 간에 상호 작용이 일어나지 않는다’라는 의미도 포함한다.

번역체라 조금 어렵게 다가왔지만 저 단락을 이렇게 해석 해  볼 수 있다.
메서드로 전달하기 때문에 해당 메서드가 포함되어 있는게 어떤 객체(즉 가변 공유 객체) 라면 다시말해 메서드만 사용할 수 있다면 공유 객체 자체는 사용 가능 한 상태(동시성 이슈가 생기지 않는 상태) 이므로 병렬성을 얻을 수 있다.

### 어떤 자료를 참고하였나요?

https://velog.io/@developerwan/Synchronized-vs-CAS%EA%B0%80-%EC%86%8D%EB%8F%84-%EC%B0%A8%EC%9D%B4%EA%B0%80-%EB%82%98%EB%8A%94-%EC%9D%B4%EC%9C%A0%EA%B0%80-%EB%AD%98%EA%B9%8C

**Comment by ay-eonii** [comment]
> 메서드로 전달하기 때문에 해당 메서드가 포함되어 있는게 어떤 객체(즉 가변 공유 객체) 라면 다시말해 메서드만 사용할 수 있다면 공유 객체 자체는 사용 가능 한 상태(동시성 이슈가 생기지 않는 상태) 이므로 병렬성을 얻을 수 있다.

`메서드만 사용할 수 있다면 공유 객체 자체는 사용 가능 한 상태(동시성 이슈가 생기지 않는 상태)`라는 말이 이해가 잘 안 되네요 ㅜㅜ 
메서드의 사용여부와 동시성 이슈와 어떤 관련이 있는 건가요?

> 메서드가 상호작용을 하지 않는다면 가변 공유 객체를 통해 공짜로 병렬성을 누릴 수 있다.

위 문장을 바탕으로 제가 이해한 바를 말씀드리자면
+ 상호작용하지 않는다 = 서로 독립적이다
+ 가변 공유 객체 = 변경가능하고 여러 메서드에서 접근 가능한 객체

위 내용을 조합해 가변적인 값이지만 각 메서드에 영향을 받지 않는다면 병렬성을 누릴 수 있다는 의미로 받아들였습니다. 

제가 잘못 이해한 부분이 있다면 코멘트 부탁드려요 ☺️

**Comment by rootTiket** [comment]
아 제가 이해한 바 로는 메서드 참조를 사용하지 않을 경우 인스턴스의 메서드를 실행 -> 해당 결과를 넘겨주는 형태로 사용 될 것인데 이 경우 공유 변수인 인스턴스 자체에 다른 스레드가 접근 할수 없다,(혹은 그 순서를 보장 할 수 없다) 즉 안정적인 병렬성을 유지할 수 없다는 의미로 받아들였습니다! (동시성 이슈가 있을 수 있으니까요)
혹시 제가 잘못 이해한 부분이 있을까요?
