### ISSUE TITLE
[question] 전략 패턴의 핵심은 전략 인가요, 런타임 인가요?

### ISSUE THREAD

**Issue by ay-eonii** [Leets-Official/modern-java-in-action#12]
### 전략 패턴의 핵심은 전략 인가요, 런타임 인가요?

> 전략 디자인 패턴은 각 알고리즘（전략이라 불리는）을 캡슐화하는 알고리즘 패밀리를 정의해둔 다음에 런타임에 알고리즘을 선택하는 기법
> p.73
<img width="708" alt="image" src="https://github.com/Leets-Official/modern-java-in-action/assets/110026001/1296211f-c2b2-4f9a-82bd-6470ccc6b124">

```java
interface NotificationStrategy {
    void notify(User user, Message message);
}
```

```java
class EmailNotificationStrategy implements NotificationStrategy {
    ....
}
```

```java
class SMSNotificationStrategy implements NotificationStrategy {
    ....
}
```

```java
// Sort by email
Collections.sort(alarm, new EmailNotificationStrategy());

// Sort by sms
Collections.sort(alarm, new SMSNotificationStrategy());
```

위 예제에서는 **알고리즘 패밀리(전략)** 을 NotificationStrategy를 구현함으로써 정의합니다. 그리고 Collections.sort의 두번째 파라미터로 넘겨주어 **런타임** 에 전략이 결정됩니다.

두 가지 키워드 모두 만족하는 군요. 누가봐도 전략패턴을 적절히 사용했습니다.

--- 

그렇다면 나아연의 코드는 어떨까요?

아래는 제가 Leets 미션 코드입니다. GuessStatus는 게임 상태를 관리하는 클래스입니다.
Status 인터페이스를 구현한 Up, Down, Correct 를 필드로 넣어주고, GuessStatus enum의 `narrowRange()`, `isContinue()`를 호출할 때 각 객체(Up, Down, Correct)의 메서드가 실행됩니다.

```java
public interface Status {

    GuessRange narrowRange(GuessRange guessRange, GuessValue guessValue);

    boolean isValid(int gap);

    boolean isContinue();
}
```
```java
public enum GuessStatus {

    UP(new Up()),
    DOWN(new Down()),
    CORRECT(new Correct());

    private final Status status;

    ...

    public GuessRange narrowRange(GuessValue guessValue, GuessRange guessRange) {
        return status.narrowRange(guessRange, guessValue);
    }

    public boolean isContinue() {
        return status.isContinue();
    }
}
```

**알고리즘 패밀리(전략)** 을 Status를 구현함으로써 정의하였지만, 어떤 전략을 사용할 지 런타임에 결정하는 건 아닌 것 같아요.

그렇다면 이는 전략패턴일까요, 아닐까요?

<br>

### 해당 문제에 대해 본인이 알고 있는 부분을 작성해주세요.

이번 장은 동작 파라미터화에 관한 장인데, 조금 주제와 벗어난 이야기 같아 일단 죄송합니다.

알고있는 부분은 위 부분에서 작성한 게 전부입니다🤪

**Comment by KoungQ** [comment]
제 생각엔 전략 패턴의 핵심은 알고리즘 캡슐화(전략)와 변경 가능한 유연성(런타임) 모두라고 생각해요.

그리고 아연님이 이슈에 올린 코드 만으론 생각이 정리되지 않아 코드 전체 흐름을 살펴본 결과,
`NumberGameMachine`과 `AlphabetGameMachine`의 `play` 메서드 안에서 `GuessStatus`가 처음으로 정의되는데 이를 타고 들어가다보면 `GuessStatus`의 `match` 메서드에서 받은 파라미터에 따라 `Up`, `Down`, `Correct`가 결정된다고 판단했어요.
따라서 컴파일 이전까지는 세 클래스(구체적인 전략들) 중 어떤 클래스가 선택될 지는 알 수 없고, 컴파일 이후 사용자의 입력에 따라 결정된다고 생각해서

> 그렇다면 이는 전략패턴일까요, 아닐까요?

에 대한 제 생각은 전략 패턴을 잘 사용하셨다고 생각합니다!

다른 의견 있다면 편하게 말씀 부탁드립니다~

**Comment by jwnnoh** [comment]
위의 경규님 말씀대로 전략 패턴의 핵심은 `캡슐화`랑 `유연성`에 의해 결정된다고 생각합니다.
해당 코드만 바라보았을 때, `유연성`을 만족시키지 못해 전략 패턴을 충족시키지 못한다고 생각합니다!

미리 생성해 둔 `UP`, `DOWN`, `CORRECT`가 런타임에 따라 유동적으로 관리되지 않고 미리 정의되어 있고,
무엇보다 런타임에 새로운 값이 추가되거나 변경되지 않는다고 판단했기에, `캡슐화`는 만족했어도 `유연성`을 만족시키지는 않았다고 생각했습니다.

> 그렇다면 이는 전략패턴일까요, 아닐까요?

이에 대한 제 답은, `아니오`입니다!

짧은 식견이어서..지적해주시면 겸허히 받아들이겠습니다!🙇

**Comment by ay-eonii** [comment]
@KoungQ 

전체 코드까지 확인해주시다니... 감사합니다 ☺️

제가 조금 더 서치해보았는데, 제 결론부터 말씀드리겠습니다. 

제가 사용한 것은 전략패턴보다는 [**상태패턴**](https://www.robotstory.co.kr/raspberry/?vid=80)에 가까운 것 같아요.
전략패턴과 상태패턴은 유사한 부분이 많아 둘의 차이점과 관련해서 많은 글들이 있더라구요😵‍💫

둘의 차이점을 간단하게 정리하자면, 
> 전략 패턴은 클라이언트가 상태를 설정하는 반면, 상태 패턴은 내부에서 자체적으로 상태를 변경한다

로 이해했습니다!

<br>

경규님께서 위 인용과 경규님이 말씀해주신 부분을 다시 읽어보면 더 전략패턴 아닌가? 라고 생각이 들 수도 있는데,

> GuessStatus의 match 메서드에서 받은 파라미터에 따라 Up, Down, Correct가 결정된다고 판단했어요.

(사실 Up, Down, Correct이 GuessStatus인지, Status인지 파악하지 못했습니다. 여기서는 GuessStatus을 지칭하는 맥락으로 읽어주세요)

match에서 받은 파라미터에 의해  Up, Down, Correct(GuessStatus)가 결정되는 것은 맞지만, 이것은 전략이 아니라고 생각해요! 각 enum의 필드로 가지고 있는 것(Status)이 전략이라고 생각합니다. 전략패턴의 목적을 고려해보자면 Up이라는 상태에서 어떤 행위를 할지, 클라이언트(외부)에서 결정하는 것이 전략패턴인데, 현재는 GuessStatus.Up은 Status.Up과 내부적으로 매핑되어 있는 상태라고 생각합니다! 

그래서 결론적으로 상태패턴과 더 가깝지 않은가 라는 생각이에요 😅

감사합니다 😊
