### ISSUE TITLE
[question] 메소드 참조가 쓰여서 좋지 않은 코드가 된걸까요?

### ISSUE THREAD

**Issue by rootTiket** [Leets-Official/modern-java-in-action#13]
### 무엇이 어려웠나요?

이 책을 읽으면서 스트림과 람다를 적극적으로 활용하기 위해 노력하고 있습니다.
코드를 작성하던중 ..

``` java
public String getAttendanceRates(Authentication authentication) {
        User user = userRepository.findById(authentication.getName()).get();
        LocalDateTime date = LocalDateTime.now();
        double trueValue = attendanceRepository.findByUserAndIsAttend(user,true).size();
        double dateSize = attendanceRepository.findByUser(user).stream().filter(a -> a.getWeek() <= dateToInt(date)).toList().size();
        double result = (trueValue / dateSize) * 100;
        return (int) result + "%";
    }
```
위 코드를 **메소드 참조**를 이용해보면 어떨까? 하는 생각이 들었습니다.

**문제의 코드**
```java
double dateSize = attendanceRepository.findByUser(user).stream().filter(a -> a.getWeek() <= dateToInt(date)).toList().size();
```

❓ 코드에 대한 설명
attendance 객체마다 **주차**가 정해져 있고 현재 조회하는 날짜 이전 까지의 주차를 모두 가져와서 그 개수를 반환하는 코드입니다.

**메소드 참조를 사용한 코드**
```java
private boolean isBefore(Attendance attendance) {
        return attendance.getWeek() <= dateToInt(LocalDateTime.now());
    }

double dateSize = attendanceRepository.findByUser(user).stream().filter(this::isBefore).toList().size();
```
isBefore 메소드를 따로 구현하고 메소드 참조를 이용하여 구현하였습니다.
두 코드중 어떤 코드가 더 좋은 코드인지 궁금합니다 :)

### 해당 문제에 대해 본인이 알고 있는 부분을 작성해주세요.

한번 밖에 쓰이지 않는 코드이기 때문에 굳이 명시적으로 선언할 필요는 없다고 느끼고는 있는데 가독성의 관점, 그리고 다른 분들의 의견도 궁금합니다
챕터 3에 깊은 관련이 있는 질문은 아니지만 한번쯤 같이 생각해봤으면 좋겠어요!

**Comment by jwnnoh** [comment]
가독성의 관점에서 해당 코드를 바라본다면, 행위를 명확히 표시한 메서드를 통한 참조가 더욱 좋아보이는 것 같습니다 :)

해당 메서드가 당장은 한 번밖에 쓰이지 않더라도, 
추후에 다른 로직에 적용될 가능성도 고려하면 `메서드 참조`를 실천하는 것이 보다 바람직하다고 생각하는 바입니다!
