### ISSUE TITLE
[question] 성능이 덜 좋은 내부 반복이 좋을까요? 성능이 더 좋은 외부 반복이 좋을까요?

### ISSUE THREAD

**Issue by yechan-kim** [Leets-Official/modern-java-in-action#24]
### 무엇이 어려웠나요?

# 내부 반복이란?
> [!note]
> 스트림에서 사용되는 반복으로, 내부에서 반복을 알아서 처리하고, 병렬성을 알아서 관리합니다.

# 외부 반복이란?
> [!note]
> 컬렉션에서 주로 사용되는 반복으로, 시용자가 직접 요소를 반복해야하고, 병렬성을 스스로 관리해야합니다.

# 스트림 API의 단점
> [!caution]
> 스트림 API는 중간 및 최종 연산, 파이프라인 오버헤드, 그리고 병렬 처리와 관련된 추가적인 비용 때문에 비싼 연산입니다.

>  [!important]
> 하지만 스트림 연산은 병렬 처리를 통해 성능을 극대화 할 수 있어, 외부 반복을 사용하는 경우 보다 대부분 좋은 성능을 보여줍니다.

# 그렇다면 컬렉션을 사용했을 때 더 우수한 성능이 나오는 경우라면 어떤 코드를 사용해야 하나요?
아래의 코드는 외부 반복이 내부 반복보다 더 우수한 성능을 내는 간단한 예제 코드입니다.
```java
import java.util.ArrayList;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        List<Integer> numbers = new ArrayList<>();
        for (int i = 0; i < 1000000; i++) {
            numbers.add(i);
        }

        // 외부 반복
        long startTime = System.nanoTime();
        int sum = 0;
        for (Integer number : numbers) {
            sum += number;
        }
        long endTime = System.nanoTime();
        System.out.println("외부 반복 소요 시간: " + (endTime - startTime) + " ns");

        // 내부 반복
        startTime = System.nanoTime();
        int sum2 = numbers.stream().mapToInt(Integer::intValue).sum();
        endTime = System.nanoTime();
        System.out.println("내부 반복 소요 시간: " + (endTime - startTime) + " ns");
    }
}
```
결과는 다음과 같습니다.
``` java
외부 반복 소요 시간: 3290375 ns // 3.290375 ms
내부 반복 소요 시간: 5421208 ns // 5.421208 ms
```

위의 예제는 단순한 예제이다 보니 대부분 외부 반복을 사용할 것으로 생긱이 됩니다. 하지만, 더 복잡한 코드가 나오고 성능차이가 더 큰 경우는 어떨까요?

코드가 복잡한 대신에 성능이 더 나은 경우가 좋을까요? 아님 코드가 간결한 대신에 성능이 덜 좋은 경우가 좋을까요? 아님 둘 다 가져갈 수 있는 방법이 있을까요?

### 해당 문제에 대해 본인이 알고 있는 부분을 작성해주세요.

요즘은 하드웨어의 발달도 성능에 대한 제한이 많이 완화되었다고 생각합니다.
그래도 성능 개선은 개발할 때 중요한 요소 중 하나라고 생각합니다.

요즘 추세는 하드웨어의 발달로, 간결하고 깔끔한 코드를 작성하는 것이 우선시 되는 것으로 알고 있습니다. 하지만 성능 차이가 크다면 저는 성능을 챙기는 것이 여러모로 좋다고 생각하고 있습니다.

성능과 코드의 간결함 중 하나만 챙길 수 있다면 어느 것을 챙기는 것이 좋을지 여러분들의 생각이 궁금합니다.

**Comment by 1winhyun** [comment]
우리 교제를 보면 외부반복을 쓰는 컬렉션의 경우 컬렉션에 추가 전에 모든 요소가 계산되어야하고 내부반복을 쓰는 스트림의 경우 사용자가 요청할 때만 값을 계산한다고 하였습니다. 그렇다고 성능의 차이가 매우 커질 정도로 복잡한 코드를 사용할 경우라면 외부반복이 내부반복보다 성능이 좋은 경우도 나올 수 있는건가요??
