### ISSUE TITLE
[recap] 연습문제 풀이

### ISSUE THREAD

**Issue by rootTiket** [Leets-Official/modern-java-in-action#30]
### 무엇을 알게 되었나요?

연습문제를 풀어봤습니다!

```java
 // 1. 2011년에 일어난 모든 트랜잭션을 찾아 값을 오름차순으로 정리하시오.
        List<Transaction> tr2011 = transactions.stream()
            .filter(t -> t.getYear() == 2011)
            .sorted(Comparator.comparing(Transaction::getValue))
            .toList()

        System.out.println(tr2011);

        // 2. 거래자가 근무하는 모든 도시를 중복 없이 나열하시오.
        List<String> cities = transactions.stream()
            .map(t -> t.getTrader().getCity())
            .distinct()
            .toList()
        System.out.println(cities);

        // 3. 케임브리지에서 근무하는 모든 거래자를 찾아서 이름순으로 정렬하시오.
        List<Trader> traders = transactions.stream()
            .map(Transaction::getTrader)
            .filter(t -> t.getCity().equals("Cambridge"))
            .distinct()
            .sorted(Comparator.comparing(Trader::getName))
            .toList();
        System.out.println(traders);

        // 4. 모든 거래자의 이름을 알파벳순으로 정렬해서 반환하시오.
        List<String> traderNames = transactions.stream()
            .map(t -> t.getTrader().getName())
            .distinct()
            .sorted()
            .toList();
        System.out.println(traderNames);

        // 5. 밀라노에 거래자가 있는가?
        boolean milanBased = transactions.stream()
            .anyMatch(t -> t.getTrader().getCity().equals("Milan"));
        System.out.println(milanBased);

        // 6. 케임브리지에 거주하는 거래자의 모든 트랜잭션값을 출력하시오.
        transactions.stream()
            .filter(t -> t.getTrader().getCity().equals("Cambridge"))
            .map(Transaction::getValue)
            .forEach(value -> System.out.println(value));

        // 7. 전체 트랜잭션 중 최댓값은 얼마인가?
        int highestValue = transactions.stream()
            .map(Transaction::getValue)
            .max(Integer::compare)
            .orElse(0);
        System.out.println(highestValue);

        // 8. 전체 트랜잭션 중 최솟값은 얼마인가?
        int lowestValue = transactions.stream()
            .map(Transaction::getValue)
            .min(Integer::compare)
            .orElse(0);
        System.out.println(lowestValue);
    }
}
```

### 어려운 내용이 있었다면 이를 어떻게 해결하였나요?

어려운건 딱히 없었는데 리스트로 변환하는 함수가 책에서는 ```.collect(toList)```를 쓰길래 찾아봤는데 최신문법은 ```toList()```라고 합니다.
자바 16부터 간결하게 바뀌었다고 해요

**Comment by ay-eonii** [comment]
책에서 사용하는 `.collect(toList)`는 `.collect(Collectors.toList())`에서 `Collectors`를 static import 한 것입니당
<img width="415" alt="스크린샷 2024-05-31 오후 11 52 48" src="https://github.com/Leets-Official/modern-java-in-action/assets/110026001/f93c0276-b7a8-497b-a2d9-fbbe7b1a697a">

<br>

그리고 `toList()`는 Stream에서, `Collectors.toList()`는 Collectors에서 지원하는 거라 차이가 있습니다. 어떤 차이인지 알아보시면 도움이 될 것 같아요!
<img width="420" alt="image" src="https://github.com/Leets-Official/modern-java-in-action/assets/110026001/b8121df4-9f10-4f44-ae2b-ed26bbd46294">

**Comment by rootTiket** [comment]
### 1. Stream.toList()

#### 특징:
- Java 16에서 도입되었습니다.
- `Stream` 인터페이스에 직접 포함되어 있습니다.
- **Immutable List**를 반환합니다.
- 반환된 리스트는 `unmodifiable`이기 때문에, 수정하려고 하면 `UnsupportedOperationException`이 발생합니다.

#### 예제:
```java
List<String> list = stream.toList();
```

#### 장점:
- 코드가 간결해집니다.
- 결과 리스트가 변경되지 않도록 보장합니다.

#### 단점:
- Java 16 이상에서만 사용 가능합니다.

### 2. Collectors.toList()

#### 특징:
- Java 8부터 사용 가능합니다.
- `Collectors` 클래스에 포함되어 있습니다.
- **Mutable List**를 반환합니다.
- 반환된 리스트는 기본적으로 `ArrayList`이며, 필요에 따라 변경할 수 있습니다.

#### 예제:
```java
List<String> list = stream.collect(Collectors.toList());
```

#### 장점:
- Java 8 이상에서 사용할 수 있습니다.
- 반환된 리스트를 자유롭게 수정할 수 있습니다.

#### 단점:
- 리스트가 변경될 수 있어, 불변성을 유지해야 하는 경우에 적합하지 않습니다.
- 코드가 다소 장황해질 수 있습니다.

### 결론

- **Java 16 이상**: 간단하게 리스트로 변환하고 불변 리스트를 원한다면 `Stream.toList()`를 사용하세요.
- **Java 8 ~ 15**: `Collectors.toList()`를 사용하세요.
- **리스트 수정 필요**: 반드시 `Collectors.toList()`를 사용하세요.

두 메서드의 선택은 주로 사용하는 Java 버전과 리스트의 불변성을 요구하는지 여부에 따라 결정됩니다. Java 16 이상에서는 불변 리스트를 간편하게 생성할 수 있는 `Stream.toList()`를 사용하는 것이 좋습니다. 그렇지 않으면 `Collectors.toList()`를 사용하면 됩니다.

라고합니다
