### ISSUE TITLE
[recap] 스트림 커스텀 컬렉터 실습

### ISSUE THREAD

**Issue by KoungQ** [Leets-Official/modern-java-in-action#33]
### 무엇을 알게 되었나요?

_현재 내가 진행하고 있는 프로젝트 내에서 필요한 기능 중 하나를 커스텀 컬렉터를 통해 구현해보면서 공부해보기로 마음먹었다._

DB에 저장된 경기들 중 상태가 `WAITING`인 경기들을 가져오는 코드를 구현해봤다.
클래스는 다음과 같다.

### 구현 클래스
``` java
import java.util.*;
import java.util.function.BiConsumer;
import java.util.function.BinaryOperator;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.stream.Collector;

public class WaitingGameCollector implements Collector<Game, Map<Boolean, List<Game>>, Map<Boolean, List<Game>>> {

    @Override
    public Supplier<Map<Boolean, List<Game>>> supplier() {
        return () -> new HashMap<Boolean, List<Game>>() {{
            put(Boolean.TRUE, new ArrayList<Game>());
            put(Boolean.FALSE, new ArrayList<Game>());
        }};
    }

    @Override
    public BiConsumer<Map<Boolean, List<Game>>, Game> accumulator() {
        return (Map<Boolean, List<Game>> acc, Game game) -> {
            acc.get(game.isWaiting())
                    .add(game);
        };
    }

    @Override
    public BinaryOperator<Map<Boolean, List<Game>>> combiner() {
        return (Map<Boolean, List<Game>> m1,
                Map<Boolean, List<Game>> m2) -> {
            m1.get(Boolean.TRUE).addAll(m2.get(Boolean.TRUE));
            m1.get(Boolean.FALSE).addAll(m2.get(Boolean.FALSE));

            return m1;
        };
    }

    @Override
    public Function<Map<Boolean, List<Game>>, Map<Boolean, List<Game>>> finisher() {
        return Function.identity();
    }

    @Override
    public Set<Characteristics> characteristics() {
        return Collections.unmodifiableSet(
                EnumSet.of(Characteristics.IDENTITY_FINISH, Characteristics.CONCURRENT));
    }
}
```
<br>

### 설명
- `supplier`에는 key가 상태 값(`isWaiting`)에 따라 true와 false로 구분되는 빈 맵을 만듦
- `accumulator`에는 판별하려는 객체의 상태값이 'WAITING' 인지 구별하여 리듀싱함
- 내 로직 상 순차적으로 진행하지 않아도 되므로 병렬 처리를 위한 메서드를 `combiner`에 담음
- `finisher`에는 객체 그대로를 사용할 것이기 때문에 `Function.Identity()`를 리턴했음
- `characteristics`는 병렬 처리가 가능하므로 CONCURRENT와 IDENTITY_FINISH를 담았다.

<br>

### 서비스 코드

서비스 코드는 다음과 같다.
``` java
...
public List<GameResponseDto> getWaitingGames() {
    List<Game> games = gameRepository.findAll();

    Map<Boolean, List<Game>> gameStatusMap = games.parallelStream()
            .collect(new WaitingGameCollector());

    return gameStatusMap.get(true).stream()
            .map(GameResponseDto::new)
            .collect(Collectors.toList());
}
...
```

DB에서 모든 데이터를 불러온 뒤 병렬 스트림으로 커스텀 컬렉터를 인스턴스화 하여 값을 가져왔고, 상태 값이 `WAITING` 값만 추출했다.

<br>

### DB

<img width="273" alt="image" src="https://github.com/Leets-Official/modern-java-in-action/assets/96408601/bc39cf76-20a3-440e-a65d-a6be3d3ad774">

> DB에 더미데이터들 중 일부 컬럼만 가져왔다.

<br>

### 테스트

``` json
{
    "code": 200,
    "message": "Success",
    "data": [
        {
            "id": 1,
            "status": "WAITING"
        },
        {
            "id": 2,
            "status": "WAITING"
        },
        {
            "id": 4,
            "status": "WAITING"
        },
        {
            "id": 5,
            "status": "WAITING"
        },
        {
            "id": 6,
            "status": "WAITING"
        },
        {
            "id": 11,
            "status": "WAITING"
        }
    ]
}

```

<br>

### 테스트 성공!
원하는 상태 값을 가진 데이터만 잘 추출됐다!
하지만 직접 쿼리를 통해 필터링 된 값들을 가져오는 게 더 효율적인지, 이렇게 모든 값을 가져오고 코드 내에서 필터링 하는 게 더 효율적일진 몰라서 도입하진 않을 듯 싶다..!

그래도 스트림으로 데이터 수집하는 것에 대한 내용은 잘 이해된 것 같아서 기부니 좋당

<br>

_아직 프로토타입 진행 중이라 DB 테이블 명과 컬럼 아이디 명이 다른 매우 불편한 부분은 눈 감아주세요.. 수정이 빈번해서 이제 보고 고쳤습니당,, ㅎ_

<br><br>

### 어려운 내용이 있었다면 이를 어떻게 해결하였나요?

반복해서 읽었습니당

### 어떤 자료를 참고하였나요?

책

**Comment by rootTiket** [comment]
> 하지만 직접 쿼리를 통해 필터링 된 값들을 가져오는 게 더 효율적인지, 이렇게 모든 값을 가져오고 코드 내에서 필터링 하는 게 더 효율적일진 몰라서 도입하진 않을 듯 싶다..!

라고 하셨는데 조금 찾아보아서 공유드립니다! 데이터 양이 적을 경우는 그 둘의 성능차이는 거의 없다고 합니다.
하지만 데이터 양이 많은 경우 전체 데이터를 가져오게 되면 성능이 굉장히 저하됩니다.
즉 코드에서 필터링하기 위해 DB에서 전체 데이터를 퍼올리는 연산 자체가 성능에 치명적이기 때문에 최대한 필터링을 한 상태로 데이터를 가져오는 것이 더 좋습니다!

비슷한 글을 인프런 질문글에서 찾아서 살펴보시면 좋을것 같아요 👍 
https://www.inflearn.com/questions/184494/sql-where-%EB%AC%B8-vs-java-stream-filter-%EC%84%B1%EB%8A%A5%EC%B0%A8%EC%9D%B4%EC%97%90-%EA%B4%80%ED%95%9C-%EC%A7%88%EB%AC%B8%EC%9E%85%EB%8B%88%EB%8B%A4
