### ISSUE TITLE
[question] 리듀싱 컬렉터는 절대 Optional.empty()를 반환하지 않는다람쥐?

### ISSUE THREAD

**Issue by ay-eonii** [Leets-Official/modern-java-in-action#38]
### 무엇이 어려웠나요?

1. 요약 팩토리 메서드도 리듀싱 컬렉터인가요?
> 스트림에 있는 객체의 숫자 필드의 합계나 평균 등을 반환하는 연산에도 리듀싱 기능이 자주 사용된다. 이러한 연산을 요약 연산이라 부른다.
p.203

2. 리듀싱 컬렉터는 절대 Optional.empty()를 반환하지 않나요?
> 리듀싱 컬렉터는 절대 `Optional.empty()`를 반환하지 않으므로 안전한 코드다
p.217

### 해당 문제에 대해 본인이 알고 있는 부분을 작성해주세요.

- **Collector 인터페이스**
```java
public interface Collector<T, A, R> { 
    Supplier<A> supplier();
    BiConsumer<A, T> accumulator(); 
    Function<A, R> finisher(); 
    BinaryOperator<A> combiner(); 
    Set<Characteristics> characteristics();
}
```
T는 수집될 스트림 항목의 제네릭 형식이다.
A는 누적자, 즉 수집 과정에서 중간 결과를 누적하는 객체의 형식이다.
R은 수집 연산 결과 객체의 형식(항상 그런 것은 아니지만 대개 컬렉션 형식)이다.

- **Collectors.maxBy**

```java
public static <T> Collector<T, ?, Optional<T>>
maxBy(Comparator<? super T> comparator) {
    return reducing(BinaryOperator.maxBy(comparator));
}
```
maxBy는 Optional<T>가 수집 연산 결과이다.

**Comment by jwnnoh** [comment]
```java
public class Main {

    public static void main(String[] args) {
        List<Integer> numbers = List.of();
        Optional<Integer> sum = numbers.stream().reduce(Integer::sum);
        System.out.println(sum);
    }
}
```
```java
Optional.Empty // 결과값
```

해당 예시 코드를 기반으로, 우리는 리듀싱 콜렉터가 `Optional.Empty`를 반환한다는 것을 알 수 있게 되었다!
그렇다면 책에서 언급한 `리듀싱 컬렉터는 절대 Optional.empty()를 반환하지 않으므로 안전한 코드다` 라는 것은 무슨 뜻일까?

이는 책에서의 예제 코드 내의 입력 스트림이 절대 컬렉터로 하여금 `Optional.empty()`를 반환하지 않도록 구성되어 있었기 때문이었다!
