### ISSUE TITLE
[recap] 자바 역사를 통틀어 가장 큰 변화: 자바8

### ISSUE THREAD

**Issue by 1winhyun** [Leets-Official/modern-java-in-action#6]
### 무엇을 알게 되었나요?

자바8은 간결한 코드, 멀티코어 프로세서의 쉬운 활용을 기반으로 한다. 
### 자바8의 기본이 되는 개념!!!!
1. 스트림 처리
- 스트림이란 한 번에 하나씩 만들어지는 연속되는 데이터들의 모임
- 어떤 프로그램의 출력값은 또 다른 프로그램의 입력값이 될 수 있다.
- 자바 8에서는 스트림 API가 추가되었다. 이는 원래는 한 번에 하나씩 처리를 했다면 이젠 작업을 추상화하여 일련의 스트림으로 만들어 처리할 수 있다. -> 스레드를 사용하지 않으면서 공짜로 병렬성을 가질 수 있다. 
2. 코드를 API로 전달(메소드에 코드 전달)
- 메서드를 다른 메서드로 넘겨주는 기능을 제공하는데 이를 동작 파라미터화라고 부른다. 
- 스트림 API는 연산을 파라미터화하는 코드를 전달하는 것을 기본으로 하기 때문이다.
 
### 일급값과 이급 시민 
- 프로그래밍 언어의 핵심은 값을 바꾸는 것이고 이러한 값을 일급값이라고 부른다. 
- 프로그램을 실행하는 동안 이러한 모든 구조체를 자유롭게 전달할 수 없고 이러한 구조체를 이급 시민이라고 부른다.

자바8은 이급 시민을 일급 값으로 바꿀 수 있는 기능을 추가했다. 

### 메서드 참조
![image](https://github.com/Leets-Official/modern-java-in-action/assets/140399766/2fcab0eb-df17-46d5-b1d7-9ff3b3e3c130)
이 코드를 
![image](https://github.com/Leets-Official/modern-java-in-action/assets/140399766/2a484ca4-0191-4870-9814-48d20d40e51a)
이렇게 변경할 수 있다. 
이미 isHidden이라는 함수는 이미 준비가 되어있다. 따라서 자바8의 기능인 메서드 참조(::)를 이용해서 직접 전달한다. 
약간 불편해 보일 수 있는 코드가 매우 짧고 간결하게 표현되었다. 
-> 자바8에서는 더이상 메서드는 이급값이 아닌 일급값이다. 
new를 이용한 객체참조를 통해 객체를 이리저리 주고받았던 것처럼 자바8에서는 File::isHidden을 이용해서 메서드 참조를 만들어 전달할 수 있게 되었다. 

### 코드 넘겨주기 및 람다: 익명 함수
예를 들어
![image](https://github.com/Leets-Official/modern-java-in-action/assets/140399766/9f0a2431-7734-49e9-81e7-fa28cea2df02)
요런 코드를 사용해서 
![image](https://github.com/Leets-Official/modern-java-in-action/assets/140399766/b2661039-fa9f-4032-872c-4716d59c57f3)
이렇게 메서드를 호출했다고 하자. 
메서드 참조도 사용했겠다 깔끔하다고 생각할 수도 있다.
하지만! 한두번 사용할 메서드를 정의하는건 나중가면 꽤나 귀찮아질 수 있다. 
-> 이럴 때 사용하는 것이 람다(익명 함수)다. 즉, 한번만 사용할 메서드는 따로 정의를 구현하지 않아도 된다.
![image](https://github.com/Leets-Official/modern-java-in-action/assets/140399766/441c87d5-e63f-4b02-8308-107584a5d932)

**풀리지 않는 의문!!**
1. 교제에서는 람다가 몇 줄 이상으로 길어진다면 익명의 람다보다는 메소드를 정의하고 메서드 참조를 활용하는 것이 바람직하다고 했다. 그렇다면 한두번 사용하여 굳이 메서드를 따로 정의할 필요가 없지만 코드가 길어지는 람다의 경우는 메서드 사용이 바람직할까 람다 사용이 바람직할까??
2. 멀티스레딩은 어렵다에서 스레드 API로 멀티스레딩 코드를 구현해서 병렬성을 이용하는 것은 쉽지 않다고 하였다. 각각의 스레드는 동시에 공유된 데이터에 접근하고 데이터를 갱신할 수 있으며 스레드를 잘 제어하지 못할 경우 원치 않는 방식으로 데이터가 바뀔 수 있다고 하였다. 
 이를 보고 작년 운영체제 과목에서 배웠던 race condition과 mesa semantic 문제가 비슷하다는 생각을 하였다. 이와 관련된 문제일까???

### 어려운 내용이 있었다면 이를 어떻게 해결하였나요?

사실 저는 자바를 잘 못한다고 생각하고 있으며 기본기조차 부족한 부분이 많다고 생각을 하였습니다. 
예를 들어 저희가 매주하는 미션 과제를 하는데 있어서도 어려움이 꽤나 많았습니다.

그렇기에 스터디를 공부하는 부분에 있어 어렵고 이해가 안가는 부분도 많았으며 거의 다 새로 알게 된 내용이 정말 많았습니다.

-> 그래서 조금이라도 다른분들 실력을 따라가기 위해 notion에 요점 정리를 따로 하였고 전체 공부가 끝난 후 요점 정리한 내용들을 다시 보면서 최대한 많은 부분을 이해할 수 있도록 노력하였습니다. 

### 어떤 자료를 참고하였나요?

-요점정리 노션
https://www.notion.so/Chapter-1-5ceee8b9ddd74320ae33be60b5c98ab9?pvs=4

**Comment by ay-eonii** [comment]
> 교제에서는 람다가 몇 줄 이상으로 길어진다면 익명의 람다보다는 메소드를 정의하고 메서드 참조를 활용하는 것이 바람직하다고 했다. 그렇다면 한두번 사용하여 굳이 메서드를 따로 정의할 필요가 없지만 코드가 길어지는 람다의 경우는 메서드 사용이 바람직할까 람다 사용이 바람직할까??

메서드명이 주는 이점을 포기하면서까지 긴 람다를 사용할 필요는 없다고 생각합니다!
